In [ ]:
"""
Practice on network analysis

Explore Gephi


"""

In [3]:
import re, itertools
import networkx as nx

import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
from collections import Counter

In [4]:
topic_df = pd.read_pickle('../dump/topic_df')
speech_df = pd.read_pickle('../dump/speech_clean_lemma')
dtm = pd.read_pickle('../dump/data_dtm_lemma.pkl')

FileNotFoundError: [Errno 2] No such file or directory: '../dump/data_dtm_lemma.pkl'

In [64]:
data = dtm.transpose()

## For Gephi

In [65]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,431,432,433,434,435,436,437,438,439,440
aa,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
aahhhh,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aaron,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aback,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
abalthus,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [66]:
# Find the top 30 words said in each speech
top_dict = {}
for c in data.columns:
    top = data[c].sort_values(ascending=False).head(30)
    top_dict[c]= list(zip(top.index, top.values))
words = []
for speech in data.columns:
    top = [word for (word, count) in top_dict[speech]]
    for t in top:
        words.append(t)
        
boring_words = ['say','like','just','dont','don','im',
                'ive','youll','youve','things','thing','youre','right','really','lot',
                'make','know','people','way',
                'come','thats','graduate']

In [97]:
len(words)

13230

In [102]:
most_common = pd.DataFrame(Counter([word for word in words if word not in boring_words]).most_common()[1:6000:20],
                          columns=['word','freq'])
len(most_common),most_common

(111,
            word  freq
 0          time   281
 1          mean    78
 2         human    41
 3           kid    31
 4        career    24
 ..          ...   ...
 106     inmates     1
 107     swallow     1
 108     deprive     1
 109   inflation     1
 110  objectives     1

 [111 rows x 2 columns])

In [103]:
dtm.head()

,aa,aahhhh,aaron,aback,abalthus,abandon,abandonment,abate,abbot,abbreviation,...,ômay,ôsobriety,ôtell,ôthe,ôwe,ôwhat,ôyou,ôyouõre,über,我是一只迷途的羔羊谁能引我走出迷茫哪有我重生的希望噢牧羊人啊噢牧羊人啊
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [104]:
columns_drop = [word for word in data.index.tolist() if word not in most_common.word.tolist()]
len(columns_drop)

36045

In [105]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,431,432,433,434,435,436,437,438,439,440
aa,0,0,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
aahhhh,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aaron,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aback,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
abalthus,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [106]:
data_slim = dtm.drop(columns=columns_drop)

In [107]:
data_slim

,adam,adams,air,aloha,alright,away,backlash,bacon,boy,cancer,...,time,transcript,ultimately,uniform,unless,ut,webbys,wonderful,writers,yeah
0,0,0,0,0,0,0,0,0,0,9,...,7,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,5,0,0,0,0,...,9,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,5,0,0,0,0,0,0,0,0,0
3,1,0,1,0,0,1,0,0,0,0,...,11,0,0,0,0,0,0,1,0,2
4,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,0,0,0,0,0,1,0,0,0,0,...,12,0,0,1,0,0,0,0,0,0
437,0,0,0,0,0,0,0,0,0,0,...,4,0,0,0,2,0,0,0,0,0
438,0,0,2,0,0,1,0,0,0,0,...,12,0,0,0,0,0,0,0,0,0
439,0,0,2,0,0,2,0,0,0,0,...,7,0,0,0,0,0,0,1,0,0
440,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [136]:
# Create co-currence matrix
df = data_slim.transpose().dot(data_slim)

In [140]:
df.values[[np.arange(df.shape[0])]*2] = 0
df

<ipython-input-140-62207f5998fe>:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  df.values[[np.arange(df.shape[0])]*2] = 0

,adam,adams,air,aloha,alright,away,backlash,bacon,boy,cancer,...,time,transcript,ultimately,uniform,unless,ut,webbys,wonderful,writers,yeah
adam,0.0,5.1,1.4,0.0,0.0,3.5,0.0,0.0,0.2,1.1,...,33.0,0.0,0.1,0.0,0.5,0.1,0.0,1.0,0.1,0.2
adams,5.1,0.0,1.7,0.0,0.5,3.1,0.0,0.2,1.2,0.5,...,28.4,0.2,0.8,0.7,0.6,0.0,0.0,0.9,1.5,0.5
air,1.4,1.7,0.0,0.0,0.1,16.1,0.0,0.5,4.5,10.1,...,83.6,0.9,1.8,1.0,1.8,0.4,0.0,10.4,1.3,2.8
aloha,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,...,1.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
alright,0.0,0.5,0.1,0.0,0.0,2.6,0.0,0.1,0.5,0.6,...,42.1,0.1,0.2,0.2,0.9,0.0,0.0,0.8,0.1,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ut,0.1,0.0,0.4,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,12.5,0.3,0.3,2.4,0.3,0.0,0.0,0.8,0.0,0.5
webbys,0.0,0.0,0.0,0.0,0.0,2.1,0.0,0.0,0.0,1.4,...,17.5,0.0,0.0,0.0,0.0,0.0,0.0,1.4,0.0,0.0
wonderful,1.0,0.9,10.4,0.0,0.8,26.5,0.0,0.7,8.3,9.6,...,171.5,1.9,6.0,0.7,4.7,0.8,1.4,0.0,2.5,7.0
writers,0.1,1.5,1.3,0.0,0.1,8.2,0.0,0.2,2.2,0.9,...,35.2,0.1,0.3,0.6,0.9,0.0,0.0,2.5,0.0,1.5
yeah,0.2,0.5,2.8,0.0,6.0,11.1,0.0,0.1,3.3,0.5,...,80.3,1.6,3.5,0.0,2.2,0.5,0.0,7.0,1.5,0.0

In [138]:
m = min(min(df.to_numpy().tolist()))
df = df/10
df

,adam,adams,air,aloha,alright,away,backlash,bacon,boy,cancer,...,time,transcript,ultimately,uniform,unless,ut,webbys,wonderful,writers,yeah
adam,0.0,5.1,1.4,0.0,0.0,3.5,0.0,0.0,0.2,1.1,...,33.0,0.0,0.1,0.0,0.5,0.1,0.0,1.0,0.1,0.2
adams,5.1,0.0,1.7,0.0,0.5,3.1,0.0,0.2,1.2,0.5,...,28.4,0.2,0.8,0.7,0.6,0.0,0.0,0.9,1.5,0.5
air,1.4,1.7,0.0,0.0,0.1,16.1,0.0,0.5,4.5,10.1,...,83.6,0.9,1.8,1.0,1.8,0.4,0.0,10.4,1.3,2.8
aloha,0.0,0.0,0.0,0.0,0.0,0.1,0.0,0.0,0.0,0.0,...,1.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
alright,0.0,0.5,0.1,0.0,0.0,2.6,0.0,0.1,0.5,0.6,...,42.1,0.1,0.2,0.2,0.9,0.0,0.0,0.8,0.1,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ut,0.1,0.0,0.4,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,12.5,0.3,0.3,2.4,0.3,0.0,0.0,0.8,0.0,0.5
webbys,0.0,0.0,0.0,0.0,0.0,2.1,0.0,0.0,0.0,1.4,...,17.5,0.0,0.0,0.0,0.0,0.0,0.0,1.4,0.0,0.0
wonderful,1.0,0.9,10.4,0.0,0.8,26.5,0.0,0.7,8.3,9.6,...,171.5,1.9,6.0,0.7,4.7,0.8,1.4,0.0,2.5,7.0
writers,0.1,1.5,1.3,0.0,0.1,8.2,0.0,0.2,2.2,0.9,...,35.2,0.1,0.3,0.6,0.9,0.0,0.0,2.5,0.0,1.5
yeah,0.2,0.5,2.8,0.0,6.0,11.1,0.0,0.1,3.3,0.5,...,80.3,1.6,3.5,0.0,2.2,0.5,0.0,7.0,1.5,0.0

In [141]:
df.to_csv('../dump/to_gephi.csv',sep=',')

In [ ]:
# Create co-currence matrix
df_fat = data.transpose().dot(data)
df_fat.to_csv('../dump/to_gephi_fat.csv',sep=',')

### Topic & terms for Gephi

In [1]:
topic_df

NameError: name 'topic_df' is not defined